In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import curve_fit, minimize
import collections

from lmfit import  Parameters , Minimizer  # ,  minimize

In [2]:
name_10 = []
string = ['f_1', 'f_2', 'f_3' , 'f_4' ,'f_5']
for strs in string:
    if strs == 'f_1':
        name_10.extend(['f_1' for i in range(4)])
    elif strs == 'f_2':
        name_10.extend(['f_2' for i in range(4)])
    elif strs == 'f_3':
        name_10.extend(['f_3' for i in range(4)])
    elif strs == 'f_4':
        name_10.extend(['f_4' for i in range(4)])
    else:
        name_10.extend(['f_5' for i in range(4)])
print(len(name_10))

#################################################
import random
list1 = [i for i in range(1 , 3)]
list2 = [i for i in range(3 , 5)]
list3 = [i for i in range(2 , 4)]

name_A = [random.choice(list1) for i in range(20)]
name_B = [random.choice(list2) for i in range(20)]
name_C = [random.choice(list3) for i in range(20)]

#################################################

PARAM_1 = ['ABC_'+str(i) for i in range(20)]
value_1 = np.linspace(0.0, 25., 20)

PARAM_2 = ['XYZ_'+str(i) for i in range(20)]
value_2 = np.linspace(0.0, 50., 20)

#################################################
key = ['X'+str(i) for i in range(20)]

################################################
df_param= pd.DataFrame({'PARAM_1' : PARAM_1 ,'value_1' : value_1 , 'PARAM_2':PARAM_2 ,'value_2' : value_2 , 'name_10':name_10 ,
                        'name_A':name_A,'name_B':name_B,'name_C':name_C,'key':key})




def func_plin(f , x , a, b, c):
    if f == 'f_1':
        return np.maximum(0 , minimum(1 , (x-a)/(b-a)))
    elif f == 'f_2':
        return np.maximum(0 , minimum(1 , (x-a)/(b-c)))
    elif f == 'f_3':
        return np.maximum(0 , minimum(1 , (x-a)*(b-a)))
    elif f == 'f_4':
        return np.maximum(0 , minimum(1 , (x-a)*(b-c)))
    elif f == 'f_5':
        return np.maximum(0 , minimum(1 , (x-a)*(b-c)))
    else: 
        return (1)
 
##########################################################



def model_func(pm_EY_EST , PM ,funcid , submod , df):
    if submod == 'TOT':
        y_mod = model_func_tot(pm_EY_EST , PM , df ,funcid )
    elif submod == 'PRX':
        y_mod = model_func_prx(pm_EY_EST , PM , df ,funcid )
    else:
        y_mod = model_func_cst(pm_EY_EST , PM , df ,funcid )
    return  y_mod  
##############################################################

def model_func_pmilvl(pm_EY_EST , PM , df ,funcid):
    pm_2= PM.dict_1
    dict_F = PM.dict_2
    pm_AY_1 = PM.pm_AY
    #pm_EY_1 = pm_EY_EST + pm_AY_1
    pm_EY_1 = pm_AY_1 + pm_EY_EST
    
    pmilvl = 0 
    pmilvl = pmilvl + pm_EY_1['XYZ_0']+ (df['name_1']+ pm_EY_1['ABC_0']) +pm_EY_1['XYZ_5'] + pm_EY_1['ABC_5']
    pmilvl = pmilvl + pm_EY_1['XYZ_1']- (df['name_2']/ pm_EY_1['ABC_1']) +pm_EY_1['XYZ_6'] + pm_EY_1['ABC_6']
    pmilvl = pmilvl + pm_EY_1['XYZ_2']- (df['name_3']/ pm_EY_1['ABC_2']) +pm_EY_1['XYZ_7']+pm_EY_1['ABC_7']
    pmilvl = pmilvl + pm_EY_1['XYZ_3']- (df['name_4']/ pm_EY_1['ABC_3']) +pm_EY_1['XYZ_8']+ pm_EY_1['ABC_8']
    pmilvl = pmilvl + pm_EY_1['XYZ_4']- (df['name_5']/ pm_EY_1['ABC_4']) +pm_EY_1['XYZ_9']+ pm_EY_1['ABC_9']
    
    pmilvl_1 = 0
    if funcid == 1:
        for i in range(0 , 10):
            pmilvl_1 = pmilvl_1 + func_plin(pm_2['X'+str(i)] ,df['name_12']  ,dict_F['X'+str(i)][0], dict_F['X'+str(i)][1], dict_F['X'+str(i)][2])
        
        
    return  pmilvl +  pmilvl_1                                                                      
                                  
    
####################################################################    

def model_func_tot(pm_EY_EST , PM , df ,funcid):
    pmilvl = model_func_pmilvl(pm_EY_EST , PM , df ,funcid)
    
    pm_2= PM.dict_1
    dict_F = PM.dict_2
    pm_AY_1 = PM.pm_AY
    #pm_EY_1 = pm_EY_EST + pm_AY_1
    pm_EY_1 = pm_AY_1 + pm_EY_EST
    
    tot = 0 
    tot = tot + pm_EY_1['XYZ_10']- (df['name_6']+ pm_EY_1['ABC_15']) +pm_EY_1['ABC_10'] + pm_EY_1['XYZ_15']
    tot = tot + pm_EY_1['XYZ_11']- (df['name_7']/ pm_EY_1['ABC_16']) +pm_EY_1['ABC_11'] + pm_EY_1['XYZ_16']
    tot = tot + pm_EY_1['XYZ_12']- (df['name_8']/ pm_EY_1['ABC_17']) +pm_EY_1['ABC_12'] + pm_EY_1['XYZ_17']
    tot = tot + pm_EY_1['XYZ_13']- (df['name_9']/ pm_EY_1['ABC_18']) +pm_EY_1['ABC_13'] + pm_EY_1['XYZ_18']
    tot = tot + pm_EY_1['XYZ_14']- (df['name_11']/ pm_EY_1['ABC_19']) +pm_EY_1['ABC_14'] + pm_EY_1['XYZ_19']
    
    tot_1 = 0
    if funcid == 1:
        for i in range(0 , 10):
            tot_1 = tot_1 + func_plin(pm_2['X'+str(i)] ,df['name_12']  ,dict_F['X'+str(i)][0], dict_F['X'+str(i)][1], dict_F['X'+str(i)][2])
    
    elif  funcid == 2:   
        for i in range(10 , 20):
            tot_1 = tot_1 + func_plin(pm_2['X'+str(i)] ,df['name_12']  ,dict_F['X'+str(i)][0], dict_F['X'+str(i)][1], dict_F['X'+str(i)][2])
           
    return  pmilvl + tot +  np.exp(tot_1)    

########################################################

def model_func_prx(pm_EY_EST , PM , df ,funcid):
    pm_1= PM.dict_1
    dict_f = PM.dict_2
    pm_AY = PM.pm_AY
    pm_EY = pm_EY_EST + pm_AY
    
    prx = 0 
    prx = prx + pm_EY['XYZ_0']+ (df['name_1']+ pm_EY['ABC_0']) +pm_EY['XYZ_5'] + pm_EY['ABC_5']
    prx = prx + pm_EY['XYZ_1']- (df['name_2']/ pm_EY['ABC_1']) +pm_EY['XYZ_6'] + pm_EY['ABC_6']
    prx = prx + pm_EY['XYZ_2']- (df['name_3']/ pm_EY['ABC_2']) +pm_EY['XYZ_7']+ pm_EY['ABC_7']
    prx = prx + pm_EY['XYZ_3']- (df['name_4']/ pm_EY['ABC_3']) +pm_EY['XYZ_8']+ pm_EY['ABC_8']
    prx = prx + pm_EY['XYZ_4']- (df['name_5']/ pm_EY['ABC_4']) +pm_EY['XYZ_9']+ pm_EY['ABC_9']
    prx = prx + pm_EY['XYZ_10']- (df['name_6']/ pm_EY['ABC_15']) +pm_EY['ABC_10'] + pm_EY['XYZ_15']
    prx = prx + pm_EY['XYZ_11']- (df['name_7']/ pm_EY['ABC_16']) +pm_EY['ABC_11'] + pm_EY['XYZ_16']
    prx = prx + pm_EY['XYZ_12']- (df['name_8']/ pm_EY['ABC_17']) +pm_EY['ABC_12'] + pm_EY['XYZ_17']
    prx = prx + pm_EY['XYZ_13']- (df['name_9']/ pm_EY['ABC_18']) +pm_EY['ABC_13'] + pm_EY['XYZ_18']
    prx = prx + pm_EY['XYZ_14']- (df['name_11']/ pm_EY['ABC_19']) +pm_EY['ABC_14'] + pm_EY['XYZ_19']
    
    prx_1 = 0
    if funcid == 1:
        for i in range(0 , 10):
            prx_1 = prx_1 + func_plin(pm_1['X'+str(i)] ,df['name_12']  ,dict_f['X'+str(i)][0], dict_f['X'+str(i)][1], dict_f['X'+str(i)][2])
    
    elif  funcid == 2:   
        for i in range(10 , 20):
            prx_1 = prx_1 + func_plin(pm_1['X'+str(i)] ,df['name_12']  ,dict_f['X'+str(i)][0], dict_f['X'+str(i)][1], dict_f['X'+str(i)][2])
    
    return  np.exp(prx + prx_1) 

#######################################################################

def model_func_cst(pm_EY_EST , PM , df ,funcid):
    pm_1= PM.dict_1
    dict_f = PM.dict_2
    pm_AY = PM.pm_AY
    pm_EY = pm_EY_EST + pm_AY
    
    cst = 0 
    cst = cst + pm_EY['XYZ_0']+ (df['name_1']+ pm_EY['ABC_0']) /pm_EY['XYZ_5'] - pm_EY['ABC_5']
    cst = cst + pm_EY['XYZ_1']+ (df['name_2']/ pm_EY['ABC_1']) /pm_EY['XYZ_6'] - pm_EY['ABC_6']
    cst = cst + pm_EY['XYZ_2']+ (df['name_3']/ pm_EY['ABC_2']) /pm_EY['XYZ_7']- pm_EY['ABC_7']
    cst = cst + pm_EY['XYZ_3']+ (df['name_4']/ pm_EY['ABC_3']) /pm_EY['XYZ_8']- pm_EY['ABC_8']
    cst = cst + pm_EY['XYZ_4']+ (df['name_5']/ pm_EY['ABC_4']) /pm_EY['XYZ_9']- pm_EY['ABC_9']
    cst = cst + pm_EY['XYZ_10']+ (df['name_6']/ pm_EY_1['ABC_15']) /pm_EY['ABC_10'] + pm_EY['XYZ_15']
    cst = cst + pm_EY['XYZ_11']+ (df['name_7']/ pm_EY_1['ABC_16']) /pm_EY['ABC_11'] + pm_EY['XYZ_16']
    cst = cst + pm_EY['XYZ_12']+ (df['name_8']/ pm_EY_1['ABC_17']) /pm_EY['ABC_12'] + pm_EY['XYZ_17']
    cst = cst + pm_EY['XYZ_13']+ (df['name_9']/ pm_EY_1['ABC_18']) /pm_EY['ABC_13'] + pm_EY['XYZ_18']
    cst = cst + pm_EY['XYZ_14']+ (df['name_11']/ pm_EY_1['ABC_19']) /pm_EY['ABC_14'] + pm_EY['XYZ_19']
    
    cst_1 = 0
    if funcid == 1:
        for i in range(0 , 10):
            cst_1 = cst_1 + func_plin(pm_1['X'+str(i)] ,df['name_12']  ,dict_f['X'+str(i)][0], dict_f['X'+str(i)][1], dict_f['X'+str(i)][2])
    
    elif  funcid == 2:   
        for i in range(10 , 20):
            cst_1 = cst_1 + func_plin(pm_1['X'+str(i)] ,df['name_12']  ,dict_f['X'+str(i)][0], dict_f['X'+str(i)][1], dict_f['X'+str(i)][2])
    
    return  np.exp(cst + cst_1)


def model_param(df):
    import collections
    dict_1 = {df['key'][i]:df['name_10'][i] for i in range(20)}
    dict_2 = {df['key'][i]:[df['name_A'][i],df['name_B'][i],df['name_C'][i]] for i in range(20)}
    dict_PM_1 = {df['PARAM_1'][i]:df['value_1'][i] for i in range(20)}
    dict_PM_2 = {df['PARAM_2'][i]:df['value_2'][i] for i in range(20)}
    dict_3 = {df['PARAM_1'][i]:df['key'][i] for i in range(20)}
    dict_4 = {df['PARAM_2'][i]:df['key'][i] for i in range(20)}
    
    pm_AY = Parameters()
    pm_EY = Parameters()
    for i in range(20):
        pm_AY.add('ABC_'+str(i), value =dict_PM_1['ABC_'+str(i)])
        pm_EY.add('XYZ_'+str(i), value =dict_PM_2['XYZ_'+str(i)])
        
    PM_col = collections.namedtuple('all_col' , ['dict_1','dict_2','pm_AY','pm_EY','dict_3','dict_4'])  
    PM = PM_col(dict_1=dict_1,dict_2=dict_2,pm_AY=pm_AY,pm_EY=pm_EY,dict_3=dict_3,dict_4=dict_4)
    
    return PM

################################################################

    

def model_func_fit(pm_EY_EST , PM  ,funcid , submod, df):
    y_mod = model_func(pm_EY_EST , PM  ,funcid , submod, df)
    er = y_mod - df['Y_act']
    er = er * np.sqrt(np.abs(df['wgt']))
    return er

20

In [3]:
def update_parameter(out):
    result = out.params
    a = []
    b = []
    c = []
    d = []
    e = []
    f = []
    for p in result:
        a.append(p)
        b.append(result[p].value)
        c.append(result[p].stderr)
        d.append(result[p].min)
        e.append(result[p].max)
        f.append(result[p].vary)
    return pd.DataFrame({'PM_NM':a ,'Estimate':b , 'Std. Error':c , 'min' :d ,'max':e , 'vary':f })

In [4]:
temp_1 = pd.read_csv('df_1.csv')
full_data = temp_1.append(pd.read_csv('df_2.csv'))

In [5]:
import os
class data_fetch:
    count = 1
    def __init__(self , path):
        self.data = pd.read_csv(path + str(data_fetch.count) +  '.csv')
        data_fetch.count += 1

# LMFIT implementataion with full data

In [10]:
import datetime 
from numpy import *
start_time = datetime.datetime.now() 
print ("Time start time is  : ", end = "") 
print (start_time) 

#############################################
PM = model_param(df_param)
pm_EY_EST = PM.pm_EY
funcid = 1
submod = 'TOT'
out_batch_01 = Minimizer(model_func_fit, pm_EY_EST  ,fcn_args = ( PM  ,funcid , submod,full_data) , batch = data_fetch, run_type = None)
out_batch_01 = out_batch_01.minimize()


########################################### 
end_time = datetime.datetime.now() 
print ("Time end time is  : ", end = "") 
print (end_time)

Time start time is  : 2023-06-01 17:30:13.911086
Time end time is  : 2023-06-01 17:30:17.126774

In [11]:
update_weight = update_parameter(out_batch_01)
update_weight

     PM_NM      Estimate    Std. Error  min  max  vary
0    XYZ_0  12047.383547  1.728612e+07 -inf  inf  True
1    XYZ_1     -3.712304  4.120742e+09 -inf  inf  True
2    XYZ_2  -1161.891419  4.335320e+09 -inf  inf  True
3    XYZ_3    803.172200           NaN -inf  inf  True
4    XYZ_4   -571.335636  0.000000e+00 -inf  inf  True
5    XYZ_5  -1590.417554  1.364342e+07 -inf  inf  True
6    XYZ_6   -908.916297  8.361575e+08 -inf  inf  True
7    XYZ_7   -532.357306  4.228681e+09 -inf  inf  True
8    XYZ_8   -425.985455 -0.000000e+00 -inf  inf  True
9    XYZ_9   -354.168797           NaN -inf  inf  True
10  XYZ_10  -1539.254797  4.280218e+09 -inf  inf  True
11  XYZ_11  -1911.160441  6.428849e+08 -inf  inf  True
12  XYZ_12  -1737.410963  1.084509e+10 -inf  inf  True
13  XYZ_13   -773.462822           NaN -inf  inf  True
14  XYZ_14  -1367.998890  2.434710e+07 -inf  inf  True
15  XYZ_15  -1355.051089           NaN -inf  inf  True
16  XYZ_16  -1341.607165  1.337814e+09 -inf  inf  True
17  XYZ_17  -1095.767913  1.526411e+10 -inf  inf  True
18  XYZ_18  -1142.779579           NaN -inf  inf  True
19  XYZ_19  -1842.300738  1.936579e+09 -inf  inf  True

# LMFIT implementation with data in batch

In [12]:
import datetime 
from numpy import *
start_time = datetime.datetime.now() 
print ("Time start time is  : ", end = "") 
print (start_time) 

#############################################
PM = model_param(df_param)
pm_EY_EST = PM.pm_EY
funcid = 1
submod = 'TOT'
out_batch_01 = Minimizer(model_func_fit, pm_EY_EST  ,fcn_args = ( PM  ,funcid , submod,) , batch = data_fetch, run_type = 'batch')
out_batch_01 = out_batch_01.minimize()


########################################### 
end_time = datetime.datetime.now() 
print ("Time end time is  : ", end = "") 
print (end_time)

Time start time is  : 2023-06-01 17:30:23.551576
Time end time is  : 2023-06-01 17:30:33.989806

In [13]:
update_weight = update_parameter(out_batch_01)
update_weight

     PM_NM      Estimate    Std. Error  min  max  vary
0    XYZ_0  12047.383547  1.728612e+07 -inf  inf  True
1    XYZ_1     -3.712304  4.120742e+09 -inf  inf  True
2    XYZ_2  -1161.891419  4.335320e+09 -inf  inf  True
3    XYZ_3    803.172200           NaN -inf  inf  True
4    XYZ_4   -571.335636  0.000000e+00 -inf  inf  True
5    XYZ_5  -1590.417554  1.364342e+07 -inf  inf  True
6    XYZ_6   -908.916297  8.361575e+08 -inf  inf  True
7    XYZ_7   -532.357306  4.228681e+09 -inf  inf  True
8    XYZ_8   -425.985455 -0.000000e+00 -inf  inf  True
9    XYZ_9   -354.168797           NaN -inf  inf  True
10  XYZ_10  -1539.254797  4.280218e+09 -inf  inf  True
11  XYZ_11  -1911.160441  6.428849e+08 -inf  inf  True
12  XYZ_12  -1737.410963  1.084509e+10 -inf  inf  True
13  XYZ_13   -773.462822           NaN -inf  inf  True
14  XYZ_14  -1367.998890  2.434710e+07 -inf  inf  True
15  XYZ_15  -1355.051089           NaN -inf  inf  True
16  XYZ_16  -1341.607165  1.337814e+09 -inf  inf  True
17  XYZ_17  -1095.767913  1.526411e+10 -inf  inf  True
18  XYZ_18  -1142.779579           NaN -inf  inf  True
19  XYZ_19  -1842.300738  1.936579e+09 -inf  inf  True